### PR TITLE
Rstudio needs knit command to compile (Issue 5)

### PR DESCRIPTION
**Pull request by yasirs**
This is to fix https://github.com/rstudio/bookdown-demo/issues/5

### CODE REVIEW

**Comment by jjallaire** [comment]
I think this is only true if you are not running the Preview Release of RStudio (the preview release should be able to do everything off of the `site:` entry).

**Comment by yasirs** [comment]
That's true, I don't have the Preview Release. I didn't know I needed it. Should we say so in the Readme file?

**Comment by jjallaire** [comment]
We cover it here https://bookdown.org/ in the "Getting Started" section.
Would be a good idea to add it to the README as well.

**Comment by yihui** [comment]
README has been updated. Thanks!

**Pull request closed without merging**
